// Centralisation des textes réutilisables

export const STRINGS = {
    appName: "Mutuelle ENSPY",
    loginTitle: "Connexion à la Mutuelle",
    pinTitle: "Code PIN",
    forgotPassword: "Mot de passe oublié ?",
    welcomeAdmin: "Bienvenue, Administrateur !",
    welcomeMember: "Bienvenue dans votre espace membre",
    dashboard: "Tableau de bord",
    settings: "Paramètres",
    errorTitle: "Erreur",
    successTitle: "Succès",
    logout: "Déconnexion",
    confirm: "Confirmer",
    cancel: "Annuler",
    yes: "Oui",
    no: "Non",
    retry: "Réessayer",
    loading: "Chargement...",
    add: "Ajouter",
    edit: "Modifier",
    save: "Enregistrer",
    delete: "Supprimer",
    searchPlaceholder: "Rechercher...",
    noData: "Aucune donnée disponible",
    validationError: "Veuillez vérifier les champs saisis.",
    sessionDefaultAmountInfo: `Montant agapé par défaut : 45 000 FCFA`,
    pinInfo: `Définissez un code PIN à 4 chiffres pour sécuriser votre accès rapide.`,
    pinForgot: `PIN oublié ? Vous serez déconnecté.`,
  };